<a href="https://colab.research.google.com/github/chrishg23-jpg/Community-Development-Framework/blob/main/IntoInfinity005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# IntoInfinity005 — Harmonic Anchor Extraction (Minimal)

import numpy as np

# ============================================
# 1. Transition operators (from IntoInfinity004)
# ============================================

T_logistic = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 104.67]
])

T_piecewise = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 100.06]
])

T_lorenz = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 108.79]
])

operators = {
    "logistic": T_logistic,
    "piecewise": T_piecewise,
    "lorenz": T_lorenz
}

# ============================================
# 2. Extract the harmonic anchor eigenvector
# ============================================

anchors = {}

for name, T in operators.items():
    vals, vecs = np.linalg.eig(T)
    idx = np.argmax(vals)  # index of the largest eigenvalue
    anchors[name] = {
        "lambda": vals[idx],
        "vector": vecs[:, idx]
    }

# ============================================
# 3. Print harmonic anchor results
# ============================================

for name, data in anchors.items():
    print(f"\n=== {name.upper()} ANCHOR ===")
    print("Surviving eigenvalue:", data["lambda"])
    print("Anchor eigenvector:", data["vector"])



=== LOGISTIC ANCHOR ===
Surviving eigenvalue: 104.67
Anchor eigenvector: [0. 0. 1.]

=== PIECEWISE ANCHOR ===
Surviving eigenvalue: 100.06
Anchor eigenvector: [0. 0. 1.]

=== LORENZ ANCHOR ===
Surviving eigenvalue: 108.79
Anchor eigenvector: [0. 0. 1.]


In [3]:
# ============================================
# 4. Normalise the harmonic anchor to N = 100
# ============================================

anchor_100 = {}

for name, data in anchors.items():
    v = data["vector"]
    v_norm = 100 * v  # scale so N-component = 100
    anchor_100[name] = v_norm

# Print results
for name, v in anchor_100.items():
    print(f"\n=== {name.upper()} NORMALISED ANCHOR ===")
    print(v)



=== LOGISTIC NORMALISED ANCHOR ===
[  0.   0. 100.]

=== PIECEWISE NORMALISED ANCHOR ===
[  0.   0. 100.]

=== LORENZ NORMALISED ANCHOR ===
[  0.   0. 100.]


In [4]:
# ============================================
# 5. Compare harmonic anchors across operators
# ============================================

print("Anchor comparison matrix (differences between anchors):\n")

species = list(anchor_100.keys())

for i in range(len(species)):
    for j in range(i+1, len(species)):
        s1, s2 = species[i], species[j]
        diff = anchor_100[s1] - anchor_100[s2]
        print(f"{s1} vs {s2}: {diff}")


Anchor comparison matrix (differences between anchors):

logistic vs piecewise: [0. 0. 0.]
logistic vs lorenz: [0. 0. 0.]
piecewise vs lorenz: [0. 0. 0.]


In [5]:
print("Universal harmonic anchor (HES convention): [0, 0, 100]")
print("Species-dependent amplification factors:")
for name, data in anchors.items():
    print(f"{name}: {data['lambda']}")


Universal harmonic anchor (HES convention): [0, 0, 100]
Species-dependent amplification factors:
logistic: 104.67
piecewise: 100.06
lorenz: 108.79


In [6]:
# ============================================
# 6. Test harmonic anchor stability
# ============================================

def apply_operator(T, v, steps=10):
    out = v.copy()
    for _ in range(steps):
        out = T @ out
    return out

v_anchor = np.array([0.0, 0.0, 100.0])

for name, T in operators.items():
    result = apply_operator(T, v_anchor, steps=5)
    print(f"\n=== {name.upper()} STABILITY TEST ===")
    print("Initial anchor:", v_anchor)
    print("After 5 applications:", result)



=== LOGISTIC STABILITY TEST ===
Initial anchor: [  0.   0. 100.]
After 5 applications: [0.00000000e+00 0.00000000e+00 1.25635138e+12]

=== PIECEWISE STABILITY TEST ===
Initial anchor: [  0.   0. 100.]
After 5 applications: [0.0000000e+00 0.0000000e+00 1.0030036e+12]

=== LORENZ STABILITY TEST ===
Initial anchor: [  0.   0. 100.]
After 5 applications: [0.00000000e+00 0.00000000e+00 1.52385935e+12]


In [7]:
# ============================================
# 7. Normalised stability test (N = 100 each step)
# ============================================

def iterate_with_normalisation(T, v, steps=10):
    out = v.copy()
    for _ in range(steps):
        out = T @ out
        # renormalise N-component to 100 if non-zero
        if out[2] != 0:
            out = out * (100.0 / out[2])
    return out

v_anchor = np.array([0.0, 0.0, 100.0])

for name, T in operators.items():
    result = iterate_with_normalisation(T, v_anchor, steps=5)
    print(f"\n=== {name.upper()} NORMALISED STABILITY TEST ===")
    print("After 5 normalised applications:", result)



=== LOGISTIC NORMALISED STABILITY TEST ===
After 5 normalised applications: [  0.   0. 100.]

=== PIECEWISE NORMALISED STABILITY TEST ===
After 5 normalised applications: [  0.   0. 100.]

=== LORENZ NORMALISED STABILITY TEST ===
After 5 normalised applications: [  0.   0. 100.]
