<a href="https://colab.research.google.com/github/chrishg23-jpg/Community-Development-Framework/blob/main/IntoInfinity004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# IntoInfinity004 — Minimal Eigenvalue Extraction

import numpy as np

# ============================================
# 1. Reconstructed transition operators
# ============================================

T_logistic = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 104.67]
])

T_piecewise = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 100.06]
])

T_lorenz = np.array([
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0],
    [0.0, 0.0, 108.79]
])

operators = {
    "logistic": T_logistic,
    "piecewise": T_piecewise,
    "lorenz": T_lorenz
}

# ============================================
# 2. Shape check
# ============================================

print("Matrix shapes:")
for name, T in operators.items():
    print(f"{name}: {T.shape}")

# ============================================
# 3. Eigenvalue extraction
# ============================================

spectra = {}

for name, T in operators.items():
    vals, vecs = np.linalg.eig(T)
    spectra[name] = {
        "eigenvalues": vals,
        "eigenvectors": vecs
    }

# ============================================
# 4. Print results
# ============================================

for name, data in spectra.items():
    print(f"\n=== {name.upper()} OPERATOR ===")
    print("Eigenvalues:")
    print(data["eigenvalues"])
    print("\nEigenvectors (columns correspond to eigenvalues):")
    print(data["eigenvectors"])


Matrix shapes:
logistic: (3, 3)
piecewise: (3, 3)
lorenz: (3, 3)

=== LOGISTIC OPERATOR ===
Eigenvalues:
[  0.     0.   104.67]

Eigenvectors (columns correspond to eigenvalues):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

=== PIECEWISE OPERATOR ===
Eigenvalues:
[  0.     0.   100.06]

Eigenvectors (columns correspond to eigenvalues):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

=== LORENZ OPERATOR ===
Eigenvalues:
[  0.     0.   108.79]

Eigenvectors (columns correspond to eigenvalues):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
